select * from emp;
--DESC
desc emp;
desc salgrade;

-- SELECT
SELECT EMPNO, ENAME, JOB, MGR FROM EMP;

--DISTINCT 중복 없이 출력
SELECT DISTINCT DEPTNO FROM EMP;

--ALL 중복 포함 출력
SELECT ALL DEPTNO FROM EMP;

SELECT * FROM EMP;


SELECT ENAME AS 사원명, SAL AS 월급, SAL*12+COMM AS 연봉, COMM AS 추가수당 FROM EMP;

--오름차순 정렬 ASC
SELECT * FROM EMP ORDER BY SAL;

--내림차순 정렬 DESC
SELECT * FROM EMP ORDER BY SAL DESC;

SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;

SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP WHERE EMPNO = 7566;

--AND / OR
SELECT * FROM EMP WHERE DEPTNO = 30 AND SAL = 1250;
SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN'; 

SELECT * FROM EMP  
WHERE DEPTNO=20 OR JOB = 'SALESMAN';

--FALSE != , <> , ^=
SELECT * FROM EMP
WHERE SAL != 3000;

--JOB
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'CLERK' OR JOB = 'SALESMAN';

--IN 
SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK','SALESMAN');
SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER','CLERK','SALESMAN');
SELECT * FROM EMP WHERE DEPTNO IN (10,20);

--BETWEEN
SELECT * FROM EMP WHERE SAL >=2000 AND SAL <= 3000;
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP WHERE EMPNO BETWEEN 7000 AND 7600;

--이름이 A~C으로 시작하는 사원 출력
SELECT * FROM EMP WHERE ENAME BETWEEN 'A' AND 'D';

--LIKE S% (S로 시작함), %S (S로 끝남), %S% (S가 중간에 껴있음)
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE ENAME LIKE '%M%I%';
SELECT * FROM EMP WHERE ENAME LIKE '%ER';

--LIKE _
SELECT * FROM EMP WHERE ENAME LIKE '_L%';
SELECT * FROM EMP WHERE ENAME LIKE '__A%';
SELECT * FROM EMP WHERE ENAME LIKE '_____';

--NULL
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;

--UNION (UNION , UNION ALL , MINUS , INTERSECT
SELECT EMPNO, ENAME, SAL,DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL,DEPTNO FROM EMP WHERE DEPTNO = 20;



--Q1
SELECT * FROM EMP WHERE ENAME LIKE '%S';
--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO IN(20,30) AND SAL>=2000;
--Q3-2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20 AND SAL >=2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 30 AND SAL >=2000;
--Q4
SELECT * FROM EMP WHERE SAL <2000 OR SAL>3000;
--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND  SAL NOT BETWEEN 1000 AND 2000;
--Q6
SELECT * FROM EMP WHERE COMM IS NULL AND MGR IS NOT NULL AND JOB IN ('CLERK', 'MANAGER') AND ENAME NOT LIKE '_L%';
