select * from emp;
--DESC�� ���̺� ���� ����
desc emp;
desc salgrade;

-- SELECT�� �ʿ��� ���� �̾Ƽ� ����
SELECT EMPNO, ENAME, JOB, MGR FROM EMP;

--DISTINCT�� �ߺ� ����
SELECT DISTINCT DEPTNO FROM EMP;

--ALL�� �ߺ� ���� �� �����ֱ� (����Ʈ)
SELECT ALL DEPTNO FROM EMP;

SELECT * FROM EMP;

--���� ���غ��� AS �ٿ��� �̸� �ٲٱ�
SELECT ENAME AS �̸�, SAL AS ����, SAL*12+COMM AS ����, COMM AS Ŀ�̼� FROM EMP;

--���� �������� ����Ʈ ASC
SELECT * FROM EMP ORDER BY SAL;

--���� �������� DESC
SELECT * FROM EMP ORDER BY SAL DESC;

--1���� DEPTNO ��������, 2���� SAL ��������
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;

--WHERE �̿��ؼ� �ϳ��� ��ȸ
SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP WHERE EMPNO = 7566;

--AND / OR
SELECT * FROM EMP WHERE DEPTNO = 30 AND SAL = 1250;
SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN'; 

SELECT * FROM EMP  
WHERE DEPTNO=20 OR JOB = 'SALESMAN';

--� �� ������ FALSE�� != , <> , ^=
SELECT * FROM EMP
WHERE SAL != 3000;

--JOB
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'CLERK' OR JOB = 'SALESMAN';

--IN ����
SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK','SALESMAN');
SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER','CLERK','SALESMAN');
SELECT * FROM EMP WHERE DEPTNO IN (10,20);

--SAL 2000�̻� 3000���� �̱� (BETWEEN)
SELECT * FROM EMP WHERE SAL >=2000 AND SAL <= 3000;
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP WHERE EMPNO BETWEEN 7000 AND 7600;

--�̸� A~C�� ��� ã��
SELECT * FROM EMP WHERE ENAME BETWEEN 'A' AND 'D';

--LIKE S% (S�� ����), %S (S�� ����), %S% (S�� ��)
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE ENAME LIKE '%M%I%';
SELECT * FROM EMP WHERE ENAME LIKE '%ER';

--LIKE _
SELECT * FROM EMP WHERE ENAME LIKE '_L%';
SELECT * FROM EMP WHERE ENAME LIKE '__A%';
SELECT * FROM EMP WHERE ENAME LIKE '_____';

--NULL üũ�ϱ�
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;

--������ UNION (UNION , UNION ALL , MINUS , INTERSECT
SELECT EMPNO, ENAME, SAL,DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL,DEPTNO FROM EMP WHERE DEPTNO = 20;



--Q1
SELECT * FROM EMP WHERE ENAME LIKE '%S';
--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO IN(20,30) AND SAL>=2000;
--Q3-2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20 AND SAL >=2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP WHERE DEPTNO = 30 AND SAL >=2000;
--Q4
SELECT * FROM EMP WHERE SAL <2000 OR SAL>3000;
--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND  SAL NOT BETWEEN 1000 AND 2000;
--Q6
SELECT * FROM EMP WHERE COMM IS NULL AND MGR IS NOT NULL AND JOB IN ('CLERK', 'MANAGER') AND ENAME NOT LIKE '_L%';
