--다중행 함수
--SUM(), AVG(), MAX(), MIN(), COUNT()
SELECT SUM(SAL) AS TOTAL FROM EMP;
SELECT TRUNC(AVG(SAL)) AS AVG FROM EMP;
SELECT MAX(SAL) AS MAX FROM EMP;
SELECT MIN(SAL) AS MIN FROM EMP;
SELECT COUNT(*) FROM EMP;
  
SELECT SUM(SAL) AS TOTAL,
        MAX(SAL) AS MAX,
        MIN(SAL) AS MIN,
        TRUNC(AVG(SAL)) AS AVG,
        COUNT(*) AS COUNT
FROM EMP;

SELECT SUM(SAL) AS SAL_TOTAL,
        SUM(ALL SAL) AS SAL_ALL,
        SUM(DISTINCT SAL) AS SAL_DISTINCT
FROM EMP;

--부서번호가 20번인 사람중에 제일 오래된 사람
SELECT MIN(HIREDATE) FROM EMP WHERE DEPTNO = 20;

--평균 급여 10, 20, 30
SELECT TRUNC(AVG(SAL),2) AS AVG_SAL, '10' AS DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT TRUNC(AVG(SAL),2) AS AVG_SAL, '20' AS DEPTNO FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT TRUNC(AVG(SAL),2) AS AVG_SAL, '30' AS DEPTNO FROM EMP WHERE DEPTNO = 30;

SELECT TRUNC(AVG(SAL)), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY JOB;

-- WHERE > GROUP BY > HAVING > ORDER BY
SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >=2000
ORDER BY DEPTNO, JOB;

--Q1
SELECT DISTINCT DEPTNO, TRUNC(AVG(SAL)) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) 
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC;

--Q2
SELECT JOB, COUNT(*) FROM EMP
GROUP BY JOB
HAVING COUNT(JOB) >= 3
ORDER BY JOB;

--Q3
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR, DEPTNO, COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO
ORDER BY TO_CHAR(HIREDATE, 'YYYY') DESC;


--Q4
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM, COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'O', 'X');
