--INNER JOIN
--TABLE 두개 이상을 엮어서 쓰기
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT * FROM EMP, DEPT
ORDER BY EMPNO;

SELECT * FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;

SELECT * FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

--등가 조인 (같은 COLUMN이 있음)
SELECT E.EMPNO, E.ENAME, E.MGR, E.HIREDATE, E.SAL, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.SAL>=3000
ORDER BY D.DEPTNO, E.EMPNO;


--SALGRADE
--비등가 조인
SELECT *
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

--SELF JOIN
SELECT
E1.EMPNO, E1.ENAME, E1.MGR,
E2.EMPNO AS MANAGER_EMPNO,
E2.ENAME AS MANAGER_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+); --조건을 만족하지 않더라도 표시 (NULL 포함)

--표준 방식 OUTER JOIN (RIGHT, LEFT, FULL)
SELECT
E1.EMPNO, E1.ENAME, E1.MGR,
E2.EMPNO AS MANAGER_EMPNO,
E2.ENAME AS MANAGER_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2 ON(E1.MGR = E2. EMPNO)
ORDER BY E1.EMPNO;

--Q1
SELECT
D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO AND E.SAL > 2000
ORDER BY DEPTNO;

--표준 방식
--NATURAL JOIN
SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E NATURAL JOIN DEPT D
WHERE SAL > 2000
ORDER BY DEPTNO;

--USING ()
SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN USING (DEPTNO)
WHERE SAL > 2000
ORDER BY DEPTNO;

--ON (많이 쓰임)
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
WHERE SAL > 2000
ORDER BY DEPTNO;

--Q2
SELECT
D.DEPTNO, D.DNAME, TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL, MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME
ORDER BY D.DEPTNO;

--ON
SELECT
D.DEPTNO, D.DNAME, TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL, MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
GROUP BY D.DEPTNO, D.DNAME
ORDER BY D.DEPTNO;

--Q3
SELECT
D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO(+)
ORDER BY D.DEPTNO, E.ENAME;

--표준
SELECT
D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E RIGHT OUTER JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
ORDER BY D.DEPTNO, E.ENAME;

--Q4
SELECT 
D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO, S.LOSAL, S.HISAL, S.GRADE, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
FROM EMP E, DEPT D, SALGRADE S, EMP E2
WHERE E.DEPTNO = D.DEPTNO(+) AND E.MGR = E2.EMPNO(+)
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY D.DEPTNO, E.EMPNO;

--표준 방식
--(1) NATURAL JOIN: LEFT , RIGHT , OUTER
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
FROM EMP E NATURAL JOIN DEPT D
ORDER BY DEPTNO, EMPNO;
