SELECT * FROM EMP;

--이름이 JONES보다 월급 많이 받는 사람 알고 싶다
SELECT SAL FROM EMP
WHERE ENAME = 'JONES';

SELECT * FROM EMP
WHERE SAL >  2975;

--SUB-QUERY (SELECT안에 SELECT 넣기)
SELECT * FROM EMP
WHERE SAL > (SELECT SAL FROM EMP
WHERE ENAME = 'JONES');

--존스보다 입사일이 빠른 사람
SELECT * FROM EMP
WHERE HIREDATE < 
( SELECT HIREDATE FROM EMP WHERE ENAME = 'JONES');

--이름이 ALLEN인 사원의 추가수당보다 더 많은 추가 수당을 받는 사람 구해보기
SELECT * FROM EMP
WHERE COMM > (
SELECT COMM FROM EMP WHERE ENAME = 'ALLEN');

--20번 부서에 속한 사원 중 전체 사원의 평균 급여보다 많은 급여를 받는 사원 정보
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC 
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.DEPTNO = 20 AND E.SAL > 
(SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL;

--20번, 30번 부서
SELECT * FROM EMP
WHERE DEPTNO IN (20,30)
ORDER BY DEPTNO;

--각 부서별 최고 급여
SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO;

--각 부서별 최고 급여를 받는 사람 출력 해보기
SELECT * FROM EMP
WHERE SAL IN(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY DEPTNO;

--ANY는 각각의 조건을 따로 만족시킴
SELECT * FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY DEPTNO;

SELECT * FROM EMP
WHERE SAL >= ANY (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY DEPTNO;

--ALL은 조건 모두를 만족해야함
SELECT * FROM EMP 
WHERE SAL > ALL (1000,2000,3000); --3000보다 클 경우

SELECT * FROM EMP
WHERE SAL <> ALL (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); --각 부서별 최고 월급을 받는 사람이 '아닌' 사원들


--EXISTS 한가지 조건이 존재하면 아예 TRUE
SELECT * FROM EMP
WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 10);

--Q1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO)
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');

--Q2
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S 
WHERE E.DEPTNO = D.DEPTNO 
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO ASC;

--Q3
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND D.DEPTNO = 10
AND E.JOB <> ALL (SELECT JOB FROM EMP WHERE DEPTNO = 30);